name: myrestaurant
description: Restaurant .

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.3.2
  animated_splash_screen: ^1.1.0
  awesome_dialog: ^2.0.0
  circular_profile_avatar: ^2.0.0
  cloud_firestore: ^2.1.0
  connectivity: ^3.0.3
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  filesize: ^2.0.1
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  firebase_storage: ^8.0.6
  flutter_luban: ^0.1.13
  flutter_speed_dial: ^3.0.5
  flutter_staggered_animations: ^1.0.0
  form_validator: ^0.1.7
  get: ^4.1.4
  google_fonts: ^2.1.0
  image_picker: ^0.7.5
  intl_phone_field: ^2.0.0
  material_floating_search_bar: ^0.3.4
  pandabar: ^0.1.1
  path_provider: ^2.0.1
  pin_code_fields: ^7.1.0
  responsive_framework: ^0.1.0
  settings_ui: ^1.0.0
  toggle_switch: ^0.1.9
  widget_circular_animator: ^0.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_rename_app: ^1.0.0
dependency_overrides:
  yaml: ^3.0.0-nullsafety.0
flutter_rename_app:
  application_name: Foodu Restaurant
  ##
  ##
  ##Set Flutter Launcher Icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launchericon/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
